#[macro_use]
extern crate rocket;

mod balancing;
mod db;
mod endpoints;
mod graphql_deser;
mod proving;
mod sync_status;
mod utils;
mod whitelisting;

use anyhow::Context as _;
use base_crypto::hash::HashOutput;
use base_crypto::time::Duration;
use bip32::{DerivationPath, XPrv};
use clap::{arg, Command};
use db::Db;
use futures::{SinkExt, StreamExt};
use ledger_storage::db::InMemoryDB;
use mn_ledger::{
    dust::{DustLocalState, DustNullifier, DustParameters, DustSecretKey},
    events::{Event, EventDetails},
};
use serde_json::json;
use std::sync::Arc;
use std::{path::PathBuf, str::FromStr as _};
use subxt::{OnlineClient, SubstrateConfig};
use sync_status::{SharedSyncStatus, SyncStatus};
use tokio::sync::Mutex;
use tokio_tungstenite::{
    connect_async,
    tungstenite::{self, client::IntoClientRequest, http::HeaderValue},
};
use url::Url;

type NetworkId = String;

const STABLE_STATE_ID: &str = "committed";
const LEDGER_PARAMETERS_DB_ID: &str = "ledger_parameters_key";
const WS_INDEXER_LOCALHOST: &str = "ws://127.0.0.1:8088/api/v3/graphql/ws";
const HTTP_INDEXER_LOCALHOST: &str = "http://127.0.0.1:8088/api/v3/graphql";
const NODE_LOCALHOST: &str = "ws://127.0.0.1:9944";

const DUST_DERIVATION_PATH: &str = "m/44'/2400'/0'/2/0";

#[subxt::subxt(runtime_metadata_path = "metadata.scale")]
pub mod midnight {}

#[derive(Clone)]
pub(crate) struct WalletState {
    pub(crate) dust_state: Arc<Mutex<DustLocalState<InMemoryDB>>>,
    pub(crate) locked: Arc<Mutex<std::collections::HashMap<HashOutput, DustNullifier>>>,
}

#[rocket::main]
async fn main() -> anyhow::Result<()> {
    tracing_subscriber::fmt::init();

    let matches = Command::new("Midnight Batcher")
        .version("2.0")
        .author("Enzo Cioppettini <enzo.cioppettini@midnight.foundation>")
        .about("Midnight paymaster for Paima")
        .arg(arg!(--"indexer-ws" <WEBSOCKET_URL>).default_value(WS_INDEXER_LOCALHOST))
        .arg(arg!(--"indexer-http" <HTTP_URL>).default_value(HTTP_INDEXER_LOCALHOST))
        .arg(arg!(--node <URL>).default_value(NODE_LOCALHOST))
        .arg(
            arg!(--secret <FILEPATH>)
                .default_value("./seed")
                .value_parser(clap::value_parser!(PathBuf)),
        )
        .arg(
            arg!(--network <NETWORK>)
                .value_parser(["testnet", "undeployed"])
                .default_value("undeployed"),
        )
        .arg(
            arg!(--db <PATH>)
                .value_parser(clap::value_parser!(PathBuf))
                .default_value("./db.sqlite"),
        )
        .arg(arg!(--"allowed-contract" <PATH> "a path to the 'keys' directory as generated by compact").value_parser(clap::value_parser!(PathBuf)))
        .get_matches();

    let ws_indexer = matches.get_one::<String>("indexer-ws").expect("default");
    let http_indexer = matches.get_one::<String>("indexer-http").expect("default");
    let node = matches.get_one::<String>("node").expect("default");
    let credentials = matches.get_one::<PathBuf>("secret").expect("default");
    let network_id = matches
        .get_one::<String>("network")
        .expect("default")
        .clone();
    let db = matches.get_one::<PathBuf>("db").expect("default");
    let whitelisting = matches.get_one::<PathBuf>("allowed-contract");

    info!("Indexer WS: {:?}", ws_indexer);
    info!("Indexer HTTP: {:?}", http_indexer);
    info!("File path: {:?}", node);
    info!("Wallet: {:?}", credentials);
    info!("Network: {}", network_id);

    let api = OnlineClient::<SubstrateConfig>::from_url(node)
        .await
        .context("Couldn't establish connection with the node")?;

    let whitelisting = whitelisting
        .map(whitelisting::read_constraints)
        .transpose()?;

    let indexer_ws_url = Url::parse(ws_indexer).context("Invalid indexer ws URL")?;
    let indexer_http_url = Url::parse(http_indexer).context("Invalid indexer http URL")?;

    let db = Db::open_db(db).await?;

    let seed = std::fs::read_to_string(credentials).context("Failed to read credentials")?;

    let root_seed =
        <[u8; 32]>::try_from(hex::decode(seed.trim()).context("seed should be a valid hex")?)
            .map_err(|_| anyhow::anyhow!("expected seed to contain 32 bytes"))?;

    let maybe_latest_state = db.get_state(STABLE_STATE_ID).await?;

    let initial_state = maybe_latest_state
        .as_ref()
        .map(|(_, state)| state.clone())
        .unwrap_or_else(|| {
            let initial_dust_params = DustParameters {
                // the values should be updated from the graphql event
                night_dust_ratio: 0,
                generation_decay_rate: 0,
                dust_grace_period: Duration::from_secs(0),
            };
            DustLocalState::<InMemoryDB>::new(initial_dust_params)
        });

    // I don't know the proper way of computing these yet.
    //
    // let legacy_address = legacy_address(&secret_keys);

    // info!("Legacy address {}", legacy_address);

    // let bech32_address = bech32_address(&secret_keys, network_id)?;

    // info!("Bech32 address {}", bech32_address);

    let sync_status = sync_status::SharedSyncStatus::new(SyncStatus::Syncing {
        progress: 0.0,
        notify: None,
    });

    let initial_state = Arc::new(Mutex::new(initial_state));

    let wallet_state = WalletState {
        dust_state: initial_state,
        locked: Arc::new(Mutex::new(std::collections::HashMap::new())),
    };

    let derivation_path = DerivationPath::from_str(DUST_DERIVATION_PATH)
        .unwrap_or_else(|err| panic!("Error calculating the `DerivationPath`: {err}"));
    let derived = XPrv::derive_from_path(root_seed.as_ref(), &derivation_path)
        .unwrap_or_else(|err| panic!("Error calculating the `ExtendedPrivateKey`: {err}"));

    let derived_seed = derived.private_key().to_bytes().into();

    let sk = DustSecretKey::derive_secret_key(&derived_seed);

    let indexer_task_handle = {
        let wallet_state = wallet_state.clone();
        let sync_status = sync_status.clone();
        let db = db.clone();
        let sk = sk.clone();
        let indexer_http_url = indexer_http_url.clone();

        tokio::task::spawn(async move {
            let sleep_time = std::time::Duration::from_secs(10);

            loop {
                let err = wallet_indexer(
                    db.clone(),
                    IndexerUrls {
                        indexer_ws_url: indexer_ws_url.clone(),
                        indexer_http_url: indexer_http_url.clone(),
                    },
                    wallet_state.clone(),
                    sync_status.clone(),
                    sk.clone(),
                )
                .await;

                let Err(error) = err else {
                    unreachable!("indexer task returned without error");
                };

                tracing::error!(reason=?error, "sync task stopped, restarting in: {} seconds", sleep_time.as_secs());

                // doing this will cause the submit endpoint to return
                // Service Unavailable instead of another error (like no funds
                // available).
                sync_status.on_indexer_fail().await;

                tokio::time::sleep(sleep_time).await;
            }
        })
    };

    let rocket_task_handle = tokio::task::spawn(async move {
        endpoints::rocket(
            api,
            wallet_state,
            sync_status,
            whitelisting,
            db,
            ("todo".to_string(), "todo".to_string()),
            sk.clone(),
            network_id.clone(),
        )
        .launch()
        .await
        .expect("the webserver shouldn't ever stop running");
    });

    tokio::select! {
        _ = rocket_task_handle => {
            tracing::info!("Rocket task finished");
        },
        // Just exit if the indexer task panics for some unknown reason (like
        // failing to deserialize a transaction), instead of just having broken
        // endpoints.
        // NOTE: non-panic errors are catched inside the task, so we should only
        // be here because of a panic.
        _ = indexer_task_handle => {
            tracing::error!("indexer task aborted");
        }
    };

    Ok(())
}

struct IndexerUrls {
    indexer_ws_url: Url,
    indexer_http_url: Url,
}

#[allow(clippy::too_many_arguments)]
async fn wallet_indexer(
    db: Db,
    indexer_urls: IndexerUrls,
    wallet_state: WalletState,
    sync_status: SharedSyncStatus,
    secret_key: DustSecretKey,
) -> anyhow::Result<()> {
    let maybe_latest_state = db.get_state(STABLE_STATE_ID).await?;

    let start_from = maybe_latest_state
        // technically this should be `start_index + 1`, but we get a redundant
        // event just to get the proper maxId, see the comment in `skip_first`
        // variable below
        .map(|(start_index, _)| start_index)
        .unwrap_or(0);

    tracing::info!("starting sync from {}", start_from);

    let mut req = indexer_urls
        .indexer_ws_url
        .into_client_request()
        .context("into_client_request error")?;

    req.headers_mut().insert(
        "Sec-WebSocket-Protocol",
        HeaderValue::from_static("graphql-ws"),
    );

    let (ws_stream, _) = connect_async(req)
        .await
        .context("Couldn't start websocket connection to the Midnight indexer")?;

    tracing::info!("WebSocket connection to the midnight indexer established");

    let (mut write, mut read) = ws_stream.split();

    let init_query = json!(
        {
            "id":"1",
            "type": "connection_init"
        }
    );

    write
        .send(tungstenite::Message::Text(init_query.to_string()))
        .await
        .context("failed to initialize graphql subscription")?;

    let _message = read
        .next()
        .await
        .ok_or_else(|| anyhow::anyhow!("expected a message"))?
        .context("graphql subscription error")?;

    let subscription_query = {
        let query = format!(
            r#"subscription {{
                        dustLedgerEvents(id: {start_from}) {{
                            __typename
                                id
                                raw
                                maxId
                        }}
                    }}"#,
        );

        json!({
            "id": "2",
            "type": "start",
            "payload": {
                "query": query
            }
        })
    };

    write
        .send(tungstenite::Message::Text(subscription_query.to_string()))
        .await
        .context("Failed to send subscription query initiation message")?;

    // a bit hacky, but we use this to set the current sync progress when the
    // batcher restarts, since it's possible there are no new events, and the
    // only way we can know that is by starting from a known point and checking
    // the maxId
    let mut skip_first = start_from > 0;

    while let Some(message) = read.next().await {
        match message {
            Ok(tungstenite::Message::Text(text)) => {
                let val: graphql_deser::Val = match serde_json::from_str(&text) {
                    Ok(val) => val,
                    Err(error) => {
                        tracing::error!("raw text: {}", text);
                        anyhow::bail!("json deserialization error of graphql response: {error:?}");
                    }
                };

                let event_bytes = hex::decode(val.payload.data.dust_ledger_events.raw).unwrap();

                let dust_event = midnight_serialize::tagged_deserialize::<Event<InMemoryDB>>(
                    std::io::Cursor::new(event_bytes),
                )
                .context("failed to deserialize dust event")?;

                tracing::info!("received dust event from the indexer");

                sync_status
                    .update(
                        val.payload.data.dust_ledger_events.id,
                        val.payload.data.dust_ledger_events.max_id,
                    )
                    .await;

                if skip_first {
                    skip_first = false;
                    continue;
                }

                let mut dust_state = wallet_state.dust_state.lock().await;

                if let EventDetails::DustSpendProcessed { nullifier, .. } = &dust_event.content {
                    let mut guard = wallet_state.locked.lock().await;

                    let find = guard
                        .iter()
                        .find(|(_, nul)| nullifier == *nul)
                        .map(|(key, _)| *key);

                    if let Some(key) = find {
                        tracing::info!("removed pending utxo");
                        guard.remove(&key);
                    }
                };

                if let EventDetails::ParamChange(ledger_parameters) = &dust_event.content {
                    db.persist_ledger_parameters(LEDGER_PARAMETERS_DB_ID, ledger_parameters)
                        .await?;
                };

                *dust_state = dust_state
                    .replay_events(&secret_key, &[dust_event])
                    .context("Couldn't apply dust event")?;

                db.persist_state(
                    STABLE_STATE_ID,
                    val.payload.data.dust_ledger_events.id,
                    &dust_state,
                )
                .await?;
            }
            Ok(_) => {}
            Err(e) => {
                tracing::error!("graphql suscription error: {}", e);
                anyhow::bail!("graphql subscription error: {e}");
            }
        }
    }

    Ok(())
}
